---
version: "3"
services:
  app:
    build: &app_build
      context: "app"
      args:
        RUBY_VERSION: "${RUBY_VERSION}"
        NODE_VERSION: "${NODE_VERSION}"
        RAILS_VERSION: "${RAILS_VERSION}"
        APP_NAME: "shipit"
    environment: &app_env
      TZ: "${TZ}"
      RAILS_ENV: "production"
      PORT: 3000
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 2
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_SCHEMA}"
      REDIS_URL: "redis://redis"
      DEPLOY_USER: "${DEPLOY_USER}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      HOST: "localhost"
      GITHUB_APP_ID: "${GITHUB_APP_ID}"
      GITHUB_INSTALLATION_ID: "${GITHUB_INSTALLATION_ID}"
      GITHUB_WEBHOOK_SECRET: "${GITHUB_WEBHOOK_SECRET}"
      GITHUB_PRIVATE_KEY: "${GITHUB_PRIVATE_KEY}"
      GITHUB_OAUTH_ID: "${GITHUB_OAUTH_ID}"
      GITHUB_OAUTH_SECRET: "${GITHUB_OAUTH_SECRET}"
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - ./tmp/migration_files:/opt/shipit/db/migrate
    depends_on:
      - db
      - redis
  worker:
    build:
      <<: *app_build
    environment:
      <<: *app_env
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    volumes:
      - ./tmp/migration_files:/opt/shipit/db/migrate
    depends_on:
      - db
      - redis
  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      TZ: "${TZ}"
      POSTGRES_DB: "${DB_SCHEMA}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/pgdata
  redis:
    image: "redis:${REDIS_VERSION}"
    environment:
      TZ: "${TZ}"
    volumes:
      - ./tmp/redis:/data
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
