---
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:@localhost/mydb' %>

development:
  <<: *default

production:
  <<: *default
