---
name: Docker

on:
  push:
    branches:
      - master
    tags:
      - "v*"
env:
  IMAGE_NAME: shipit-engine
  RUBY_VERSION: "2.7.1"
  NODE_VERSION: "14.9.0"
  RAILS_VERSION: "6.0.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --build-arg RUBY_VERSION="$RUBY_VERSION" --build-arg NODE_VERSION="$NODE_VERSION" --build-arg RAILS_VERSION="$RAILS_VERSION" --build-arg APP_NAME="shipit" app

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg RUBY_VERSION="$RUBY_VERSION" --build-arg NODE_VERSION="$NODE_VERSION" --build-arg RAILS_VERSION="$RAILS_VERSION" --build-arg APP_NAME="shipit" --tag $IMAGE_NAME app

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
